upstream backend_rr {
    zone upstream-backend_rr 256k;
    server 192.168.2.115:9000 sid=white slow_start=120s;
    server 192.168.2.115:9001 sid=blue  slow_start=120s;
    server 192.168.2.115:9002 sid=green slow_start=120s;
    server 192.168.2.115:9003 sid=gold  slow_start=120s;
}

upstream backend_least_conn {
    zone upstream-backend_least_conn 256k;
    least_conn;
    server 192.168.2.115:9000 sid=white slow_start=120s;
    server 192.168.2.115:9001 sid=blue  slow_start=120s;
    server 192.168.2.115:9002 sid=green slow_start=120s;
    server 192.168.2.115:9003 sid=gold  slow_start=120s;
}

upstream backend_random {
    zone upstream-backend_random 256k;
    random;
    server 192.168.2.115:9000 sid=white;
    server 192.168.2.115:9001 sid=blue;
    server 192.168.2.115:9002 sid=green;
    server 192.168.2.115:9003 sid=gold;
}

upstream backend_hash {
    zone upstream-backend_hash 256k;
    hash $scheme$request_uri;
    server 192.168.2.115:9000 sid=white;
    server 192.168.2.115:9001 sid=blue;
    server 192.168.2.115:9002 sid=green;
    server 192.168.2.115:9003 sid=gold;
}

upstream backend_hash_keepalive {
    zone upstream-backend_hash 256k;
    hash $scheme$request_uri;
    server 192.168.2.115:9000 sid=white;
    server 192.168.2.115:9001 sid=blue;
    server 192.168.2.115:9002 sid=green;
    server 192.168.2.115:9003 sid=gold;
    keepalive 32;
    keepalive_requests 1000;
    keepalive_time 1h;
    keepalive_timeout 60s;
}

upstream backend_rr_sticky_cookie {
    zone upstream-backend_rr_sticky_cookie 256k;
    server 192.168.2.115:9000 sid=white slow_start=120s;
    server 192.168.2.115:9001 sid=blue  slow_start=120s;
    server 192.168.2.115:9002 sid=green slow_start=120s;
    server 192.168.2.115:9003 sid=gold  slow_start=120s;
    sticky cookie sticky_cookie path=/rr_sticky_cookie;
    # sticky cookie sticky_cookie path=/ Httponly Secure;
    sticky_secret SomeSecretWeUseForThePersistanceCookie;
}


server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/angie/host.access.log  main;


    location / {
        proxy_pass http://backend_rr;
    }

    location /least_conn {
        proxy_pass http://backend_least_conn;
    }

    location /random {
        proxy_pass http://backend_random;
    }

    location /hash {
        proxy_pass http://backend_hash;
    }

    location /hash_keepalive {
        proxy_pass http://backend_hash_keepalive;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /rr_sticky_cookie {
        proxy_pass http://backend_rr_sticky_cookie;
    }

    location ~* ^\/only(\d\d\d\d) {
        proxy_pass http://192.168.2.115:$1;
    }

    location = /favicon.ico {
        log_not_found off; access_log off;
        return 200 "Here should be favicon.ico";
    }

    location /status/ {
        api     /status/;
        allow   127.0.0.1;
        #deny   all;
    }

    location /console/ {

        # Только локальный доступ
        allow 127.0.0.1;
        #deny all;

        auto_redirect on;

        alias /usr/share/angie-console-light/html/;
        # Только во FreeBSD:
        # alias /usr/local/www/angie-console-light/html/;
        index index.html;

        location /console/api/ {
            api /status/;
        }
    }


    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/angie/html;
    }

}
